### PR TITLE
Add Crassus (CRS) to ForkDelta.

### PR DESCRIPTION
**Pull request by pgibler**
Website: http://crassus.io
Distribution: Forum airdrops (reddit, 4chan, bitcointalk)

### CODE REVIEW

**Comment by freeatnet** [comment]
@trigunshin

**Comment by pgibler** [comment]
None so far. I'm preparing a distribution script so can send them out to any Ethereum addresses that want to participate. The idea is to open up discussions on bitcointalk & reddit to collect these addresses once that's ready, and they'll be able to be traded on any exchange that lists in soon after.

I was hoping to have Crassus listed before the airdrop occurs so we have an exchange we can direct users to so they know there is a place to buy/sell their Crassus, hence why I've opened this PR now. But if you want us to wait until then, it's understandable.

**Comment by freeatnet** [comment]
@pgibler Could you post up bitcointalk & reddit links?

**Comment by freeatnet** [comment]
Please re-file under https://github.com/forkdelta/tokenbase

**Pull request closed without merging**
