### PR TITLE
Attempt to make URLs more Google-friendly

### PR DESCRIPTION
**Pull request by freeatnet**
After a long discussion, I took a stab at making coin URLs more indexable by moving to the hashbang format of `/#!/trade/COIN-ETH`. Despite the upcoming deprecation of Google support in the summer of 2018, they are definitely much more crawler-friendly than what we have right now.

Selected token is picked up from both the new and the old `#COIN-ETH` format, but all links should now point to `/#!/trade/COIN-ETH`. Additionally, I have added hashbang URLs to ticker and token selector `a href`'s, so that a crawler knows they exist and are accessible.

Please check this out and let me know if you find any bugs with it.

### CODE REVIEW

**Comment by JonathonDunford** [comment]
Clicking a ticker link in the dropdown refreshes the page (navigates to new page).

Might be able to be solved by changing line 125955  from '/#!/trade/' to '#!/trade/'

If that doesn't solve it, you should use .preventDefault() tied to the click event to prevent the entire event from passing through.


ALSO

If .pushState is being used on live site, great. If not, we need to add .pushState() to these URL changes.

Then, this part is not on live and BROKEN currently: We need to be listening for the state changes to show the proper tickers (and update the UI) upon back/forward page navigation.

event listener code:
window.addEventListener('popstate', function(e) {

if you want to be lazy, you can just trigger a click event on the proper <a> tag in the drop down on popstate

**Comment by freeatnet** [comment]
@JonathonDunford I still can't reproduce the issue you were having with reloads; however, I've removed the absolute path references from links.

Regarding, `popstate`, I agree we should handle back-navigation; however, I'm still not sure why you think we need to use pushstate.

**Comment by JonathonDunford** [comment]
@freeatnet PushState stores the state in the browsers history. I believe it may already be doing that by the fact we can go back/forward.

Google implicitly says they look for that. The benefits are: Google says so, and it stores the URLs in your browser history so it acts as if you are naturally navigating through a site. You can also see the AJAX urls in your history.

**Comment by freeatnet** [comment]
Looks good to me!

**Comment by JonathonDunford** [comment]
<3

**Pull request merged**
