### PR TITLE
Fix ticker-to-token matching

### PR DESCRIPTION
**Pull request by freeatnet**
ED ticker data returns data indexed by `ETH_<token-symbol or first-six-characters-of-contract>`, while the frontend only looks up ticker values by `ETH_<token-symbol>`. Therefore, when we listed new tokens in #1 and #3, frontend was unable to match the new tokens to ticker data. 

This change switches from matching by `<token-symbol>` to matching ticker info to token listings by contract address (in full, as to avoid errors).

### CODE REVIEW

**Comment by wparad** [comment]
Looking at main.js it looks like compiled code.  Is that true?  And if so it is really committed as well?

**Comment by freeatnet** [comment]
@wparad Unfortunately, that's how the [parent project](https://github.com/etherdelta/etherdelta.github.io/blob/master/js/main.js) released it.

I used [prettier](https://www.npmjs.com/package/prettier) to get a readable version for myself, but applied the change to the original file directly in the end. I'll update the top post to include a diff.

**Comment by wparad** [comment]
I see.  If it is compiled code, doesn't that mean that there is a second change needed to target the compiled code, or did the parent project really change the compiled code directly?

**Comment by freeatnet** [comment]
@wparad The best explanation I got from folks associated with the parent project is that only transpiled/minified version was ever checked in, "for repo performance reasons". ¯\_(ツ)_/¯

**Comment by wparad** [comment]
I guess the question then becomes as the community improves this, what direction should we go.  Leaving as it is makes no sense.  We could try to recreate current UI decomposing the react or perhaps start fresh, improving the underlying framework choices perhaps throw in some vuejs and good development practices while we are at it.  Any suggestions on how to proceed?

**Comment by freeatnet** [comment]
@wparad I agree it makes no sense to work on the transpiled / minified code going further. This was a one-off fix by community request.

Going forward, we should have our own fully open source frontend. I've already done some groundwork using React/Redux, and should be able to publish it within the week.

**Pull request merged**
