### PR TITLE
fixes forkdelta/forkdelta.github.io#102

### PR DESCRIPTION
**Pull request by activescott**
fix for #102 . However, @JonathonDunford please review. I'm sure you had a reason to make that change (done in 272653eb8e46f909e16789f37d55234a49f2f4cf) and reverting this change may cause an issue you know to look for that I didn't see.

### CODE REVIEW

**Comment by freeatnet** [comment]
Chrome looks good; unfortunately, both Firefox and Safari still hide the navbar with this patch applied (tested on Chrome 64.0.3282.167 (Official Build) (64-bit), Safari 11.0.3 (13604.5.6), Firefox 49.0, and Firefox Beta 59.0 on macOS 10.13)

**Comment by activescott** [comment]
k. The shift does indeed still happen if I make my browser very narrow on FF. On FF it does still push it up ever-so slightly (~2 pixels) when the browser is wide but that behavior is in older versions and appears to have been around a while. While not ideal, it isn't as impactful as the bigger shift when browser is narrow (which is more like ~20px).

I'll investigate today/tonight but it might be tricky to get it done right (because css). So not sure if this will be done before tonight (but it will be done before I sleep again :wink:.

**Comment by activescott** [comment]
k. The shift does indeed still happen if I make my browser very narrow on FF. On FF it does still push it up ever-so slightly (~2 pixels) when the browser is wide but that behavior is in older versions and appears to have been around a while. While not ideal, it isn't as impactful as the bigger shift when browser is narrow (which is more like ~20px).

I'll investigate today/tonight but it might be tricky to get it done right (because css). So not sure if this will be done before tonight (but it will be done before I sleep again :wink:.

**Comment by activescott** [comment]
k. I think I found a simple and robust way to fix it. Really the css and layout is a mess here. I feel like this is a game of whack-a-mole. Maybe worth removing the fixed height stuff and trying to refactor the layout to properly use the bootstrap grid. If we could live with there being two rows where each column is split in half vertically (which I suspect might just be better UX anyway to remove some of the "lines") I think a nested bootstrap grid would give us a more robust semantic layout. I don't recommend that we invest in that though unless this front end will live for quite some time (e.g. months) _and_ we want to keep evolving it.

**Pull request merged**
