### PR TITLE
Fixes #111 by warning on unregistered token selection as well as addi…

### LINKED ISSUE #111: Warn user when opening direct contract link
The warning should communicate two main points:
* Trading by direct contract address means we have not vetted the token, and that the token is not officially listed
* Token contracts can be easily cloned, the user should seek verification of the token contract address from an official source

### PR DESCRIPTION
**Pull request by activescott**
…ng a warning to other token modal

- [ ] minify `main-unminified.js` -> `main.js`

### CODE REVIEW

**Comment by freeatnet** [comment]
Swanky!

**Comment by activescott** [comment]
@freeatnet Can you please do the minification and then merge this one? I need a reviewer to get it merged and AFAIK I don't have the script to minify (please correct me if I'm missing something).

**Comment by freeatnet** [comment]
@activescott On it.

**Comment by freeatnet** [comment]
@activescott Looks good! I noticed the warning is dismissable by clicking on the backdrop of the modal. Would you say this warning is critical enough to require a click on the "continue" button?

**Comment by activescott** [comment]
Thanks. Yes it probably should require the user to explicitly click
continue. I can look into how to change that tonight or tomorrow...

**Comment by activescott** [comment]
@freeatnet Just committed change to make it so the dialog no longer dismissable. Please review, minify, & merge if you agree it's ready 🤞 .

**Comment by freeatnet** [comment]
@activescott Timing! I was just minifying this.

**Comment by freeatnet** [comment]
@activescott Judging by your comment, you aren't too happy with dropping the dimmer. If the only reason for dropping it is disabling "click background to dismiss" behaviour, would [`closableByDimmer: false`](http://alertifyjs.com/factory.html) be better?

**Comment by activescott** [comment]
@freeatnet Yes! closableByDimmer is definitely the right way. I just pushed that commit for this one. Hopefully we'll close this one down.

**Comment by JonathonDunford** [comment]
@activescott Ping.

**Comment by activescott** [comment]
@freeatnet  I cannot get that code to trigger when using main.js. Does work if I use main-unminified.js. So it seems the issue was in the minification.

**Comment by activescott** [comment]
@freeatnet I was thinking I'll just pull this change into #130 and we'll not waste more time dealing with the minified/unminified mess.

**Comment by activescott** [comment]
Ok. I pulled this into #130 to not waste more time dealing with the minified/unminified mess. Lets test that PR get it in and forget this one.

**Pull request closed without merging**
