### PR TITLE
Request to Add DragonDRG Token

### PR DESCRIPTION
**Pull request by furusiyya**
I have provided all required information according to existing tokens. Please add if it is compliant to Forkdelta standard or make comment so I can update PR. Thanks!

### CODE REVIEW

**Comment by soliditeam** [comment]
Hi there, please assist in reviewing this

**Comment by soliditeam** [comment]
Hi there

Please assist in understanding how we would provide confirmation? If the founders send an email from drgtoken.io domain?

Dean Cannell
CoinFabric

dean@coinfabric.com
https://coinfabric.com
________________________________

**Comment by freeatnet** [comment]
Dean,

A page on https://drgtoken.io/ referencing the contract address would
suffice for verification.

We typically find it either in token details section (example: OriginTrail
<https://origintrail.io/#how-it-works>) or on the FAQ page (example:
Crypto20 <https://crypto20.com/en/portal/howto/#cryptoICOFaq>, "How do I
view C20 tokens in my wallet? / How to add C20 to my wallet?"). It can also
be in the form of a public post on an official social media channel
(example: @BitPopulous, officially linked from populous.co, tweeted
<https://twitter.com/BitPopulous/status/947465562552184832> their contract
address; Matrix AI Network website <https://www.matrixchain.io/> lists
/r/MatrixAINetwork <https://www.reddit.com/r/MatrixAINetwork/> as an
official contact, a moderator's stickied post
<https://www.reddit.com/r/MatrixAINetwork/comments/7ryv6j/matrix_faqs_read_this_first/>
contains the contract address).

We require verification to ensure the contract address in the listing is
the one intended by the token issuing entity. The verification source must
be public, so that any reviewer can access it independently.

**Comment by freeatnet** [comment]
**Reposted to get GitHub to show the links right**

Dean,

A page on https://drgtoken.io/ referencing the contract address would
suffice for verification.

We typically find it either in token details section (example: [OriginTrail]
(https://origintrail.io/#how-it-works)) or on the FAQ page (example:
[Crypto20](https://crypto20.com/en/portal/howto/#cryptoICOFaq), "How do I
view C20 tokens in my wallet? / How to add C20 to my wallet?"). It can also
be in the form of a public post on an official social media channel
(example: @BitPopulous, officially linked from [populous.co](https://populous.co), [tweeted](https://twitter.com/BitPopulous/status/947465562552184832) their contract
address; Matrix AI Network [website](https://www.matrixchain.io/) lists
[/r/MatrixAINetwork](https://www.reddit.com/r/MatrixAINetwork/) as an
official contact, a [moderator's stickied post](https://www.reddit.com/r/MatrixAINetwork/comments/7ryv6j/matrix_faqs_read_this_first/)
contains the contract address).

We require verification to ensure the contract address in the listing is
the one intended by the token issuing entity. The verification source must
be public, so that any reviewer can access it independently.

**Comment by soliditeam** [comment]
Please let me know if this is good enough, its very official :)

**Comment by freeatnet** [comment]
@soliditeam This is excellent!

**Comment by soliditeam** [comment]
cool! :)

**Comment by soliditeam** [comment]
how long does it take from now? :P

**Comment by freeatnet** [comment]
Moved to the new format https://github.com/forkdelta/tokenbase/issues/39

**Comment by soliditeam** [comment]
So has this been added?

**Comment by furusiyya** [comment]
@soliditeam Yes. Added!

**Pull request closed without merging**
