### PR TITLE
[Closes #5] Switch to MyEtherAPI.com for access to blockchain

### LINKED ISSUE #5: Switch fallback API provider to myetherapi.com?
We currently use Metamask as the default API provider. For users without Metamask, we fall back to the non-standard etherscan.io API. Users have reported their transactions being delayed at times of network congestion.

Now, the creators of MyEtherWallet.com have released a publicly accessible web3.js-compatible API, myetherapi.com. They use it to power MyEtherWallet.com.

Unfortunately, we don't have the data to quantify how bad the situation is with Etherscan, but we could switch to using it as a fallback for non-Metamask users and see if it yields an improvement via qualitative feedback.

### PR DESCRIPTION
**Pull request by freeatnet**

### CODE REVIEW

**Comment by freeatnet** [comment]
Blocked by https://github.com/MyEtherWallet/myetherapi/issues/1#issuecomment-355896945. If they block IP addresses at random, that's a no-go. Waiting on their response.

**Comment by freeatnet** [comment]
I've emailed a bit with @tayvano and it seems like it may have been a one-off event. We should be ok to proceed.

**Comment by JonathonDunford** [comment]
"If you hit over 200 requests / minute, you'll be blocked for ~1hr, regardless of region."

Need to make sure it's under 200 rpm?

**Comment by freeatnet** [comment]
@JonathonDunford This frontend currently updates the latest block number about every 5 seconds, otherwise only needing a node to send transactions. Doesn't seem like it would ever hit anywhere close to 200 rpm.

**Pull request merged**
